from __future__ import annotations

import argparse
import copy
import difflib
import pprint
import sys
import traceback
import unittest
from collections import deque
from typing import Any, List, Optional


# Generated by leetcode-init



class TreeNode:
    """Create a binary tree node used by LeetCode examples."""

    def __init__(self, val: int = 0, left: Optional[TreeNode] = None, right: Optional[TreeNode] = None):
        self.val = val
        self.left = left
        self.right = right


def build_tree(values: list[Any] | None) -> Optional[TreeNode]:
    """Build a binary tree from LeetCode level-order list data."""
    if not values:
        return None
    nodes = [None if value is None else TreeNode(value) for value in values]
    kids = nodes[::-1]
    root = kids.pop()
    for node in nodes:
        if node is None:
            continue
        if kids:
            node.left = kids.pop()
        if kids:
            node.right = kids.pop()
    return root


def serialize_tree(root: Optional[TreeNode]) -> list[Any]:
    """Convert a binary tree back into LeetCode level-order list data."""
    if root is None:
        return []
    values: list[Any] = []
    queue: deque[Optional[TreeNode]] = deque([root])
    while queue:
        node = queue.popleft()
        if node is None:
            values.append(None)
            continue
        values.append(node.val)
        queue.append(node.left)
        queue.append(node.right)
    while values and values[-1] is None:
        values.pop()
    return values


class Solution:
    def maxAncestorDiff(self, root: Optional[TreeNode]) -> int:
        """
        Given the root of a binary tree, find the maximum value `v` for which
        there exist different nodes `a` and `b` where `v = |a.val - b.val|` and
        `a` is an ancestor of `b`.
        
        A node `a` is an ancestor of `b` if either: any child of `a` is equal
        to `b` or any child of `a` is an ancestor of `b`.
        
        Examples:
        
        Example 1
        Input: root = [8, 3, 10, 1, 6, None, 14, None, None, 4, 7, 13]
        Output: 7
        
        Example 2
        Input: root = [1, None, 2, None, 0, 3]
        Output: 3
        """
        # left_diff, right_diff = 0, 0
        # if root.left == None and root.right == None:
            # return 0
        # if root.left:
            # left_diff = max(abs(root.val - root.left.val),
                            # self.maxAncestorDiff(root.left))
        # if root.right:
            # right_diff = max(abs(root.val - root.right.val),
                             # self.maxAncestorDiff(root.right))
        # return max(left_diff, right_diff)

    # def min_max_values_tree(self, node):
        # max_value, min_value = float("-inf"), float("inf")
        # max_value_left, min_value_left = float("-inf"), float("inf")
        # max_value_right, min_value_right = float("-inf"), float("inf")
        # if 
        # if node.left:
            # min_value_left = min_max_values_tree()
        # max_value = max(node.val,
                        # self.min_max_values_tree)
        # min_value = min(node.val, self.min_max_values_tree[1])

        # return min_value, max_value

    def min_values_tree(self, node):
        """Return the minimum value in the subtree rooted at `node`.

        Hint:
        - The result should consider the current node and both children.
        - Decide what a leaf node should return.
        - If one child is missing, the other side should still work cleanly.
        """
        min_value_left, min_value_right = float("inf"), float("inf")

        # Hint: what value from the current node should be compared against
        # each child's subtree minimum?
        if node.left:
            min_value_left = min(min_value_left, self.min_values_tree(node.left))

        # Hint: same issue here as on the left side.
        if node.right:
            min_value_right = min(min_value_right,
                                  self.min_values_tree(node.right))

        # Hint: are you including node.val in the final answer, even for leaves?
        return min(node.val, min_value_left, min_value_right)

    def max_values_tree(self, node):
        """Return the maximum value in the subtree rooted at `node`.

        Hint:
        - The result should consider the current node and both children.
        - Decide what a leaf node should return.
        - If one child is missing, the other side should still work cleanly.
        """
        # Hint: for a max helper, the neutral starting value should move in the
        # opposite direction from the min helper.
        max_value_left = float("-inf")
        max_value_right = float("-inf")

        # Hint: what value from the current node should be compared against
        # each child's subtree minimum?
        if node.left:
            # Hint: check whether both the variable name and recursive call match
            # the "max values" goal of this helper.
            max_value_left = max(max_value_left,
                                 self.max_values_tree(node.left))

        # Hint: same issue here as on the left side.
        if node.right:
            # Hint: if this helper is finding a maximum, check whether this
            # combine step is using the right operation.
            max_value_right = max(max_value_right,
                                  self.max_values_tree(node.right))

        # Hint: are you including node.val in the final answer, even for leaves?
        return max(node.val, max_value_left, max_value_right)


PARAM_ORDER = ['root']
PARAM_KINDS = {'root': 'tree'}
RETURN_KIND = 'plain'
EXAMPLES = [{'name': 'Example 1',
  'input': {'root': [8, 3, 10, 1, 6, None, 14, None, None, 4, 7, 13]},
  'expected': 7},
 {'name': 'Example 2', 'input': {'root': [1, None, 2, None, 0, 3]}, 'expected': 3}]


def prepare_argument(name: str, value: Any) -> Any:
    """Convert one stored example input into the expected runtime value."""
    kind = PARAM_KINDS[name]
    if kind == "tree":
        return build_tree(copy.deepcopy(value))
    if kind == "listnode":
        return build_linked_list(copy.deepcopy(value))
    return copy.deepcopy(value)


def normalize_result(value: Any) -> Any:
    """Normalize a solution result back into comparable plain data."""
    if RETURN_KIND == "tree":
        return serialize_tree(value)
    if RETURN_KIND == "listnode":
        return serialize_linked_list(value)
    return value


def format_diff(expected: Any, actual: Any) -> str:
    """Render a unified diff for mismatched expected and actual values."""
    expected_lines = pprint.pformat(expected, sort_dicts=False).splitlines()
    actual_lines = pprint.pformat(actual, sort_dicts=False).splitlines()
    diff = list(
        difflib.unified_diff(
            expected_lines,
            actual_lines,
            fromfile="expected",
            tofile="actual",
            lineterm="",
        )
    )
    return "\n".join(diff) if diff else "No diff."


def run_case(case: dict[str, Any]) -> tuple[Any, Any, str | None, str | None]:
    """Execute one example case and capture any failure mode."""
    solution = Solution()
    prepared_args = [prepare_argument(name, case["input"][name]) for name in PARAM_ORDER]
    try:
        actual = solution.maxAncestorDiff(*prepared_args)
    except NotImplementedError as exc:
        return case["expected"], f"<not implemented: {exc}>", "not_implemented", None
    except Exception as exc:  # pragma: no cover - surfaced to the caller for debugging.
        label = f"{exc.__class__.__name__}: {exc}"
        return (
            case["expected"],
            f"<exception: {label}>",
            "exception",
            "".join(traceback.format_exception(exc)).rstrip(),
        )
    return case["expected"], normalize_result(actual), None, None


def run_examples() -> None:
    """Print each parsed example and compare it against the current solution."""
    for case in EXAMPLES:
        expected, actual, error, trace = run_case(case)
        matched = error is None and actual == expected
        print(case["name"])
        print(f"Input: {case['input']!r}")
        print(f"Expected: {expected!r}")
        print(f"Actual: {actual!r}")
        print(f"Matches expected: {matched}")
        if trace:
            print("Traceback:")
            print(trace)
        if error is not None or not matched:
            print("Diff:")
            print(format_diff(expected, actual))
        print()


class GeneratedExampleTests(unittest.TestCase):
    def test_examples(self) -> None:
        """Assert that every parsed example matches the current solution output."""
        for case in EXAMPLES:
            with self.subTest(example=case["name"]):
                expected, actual, error, trace = run_case(case)
                if error == "not_implemented":
                    self.fail(f"Solution not implemented for {case['name']}: {actual}")
                if error == "exception":
                    message = f"Solution raised an exception for {case['name']}: {actual}"
                    if trace:
                        message = f"{message}\n{trace}"
                    self.fail(message)
                self.assertEqual(expected, actual, format_diff(expected, actual))


def main() -> None:
    """Run the generated CLI entrypoint for examples or unittest mode."""
    parser = argparse.ArgumentParser(description="Run the generated LeetCode scaffold.")
    parser.add_argument("--test", action="store_true", help="Run unittest checks instead of the example runner.")
    args = parser.parse_args()
    if args.test:
        unittest.main(argv=[sys.argv[0]])
        return
    run_examples()


if __name__ == "__main__":
    main()
