from __future__ import annotations

import argparse
import copy
import difflib
import pprint
import sys
import traceback
import unittest
from typing import Any, List, Optional


# Generated by leetcode-init



class Solution:
    def checkIfPangram(self, sentence):
        """
        A pangram is a sentence where every letter of the English alphabet
        appears at least once.
        
        Given a string `sentence` containing only lowercase English letters,
        return `true` if `sentence` is a pangram, or `false` otherwise.
        
        Examples:
        
        Example 1
        Input: sentence = 'thequickbrownfoxjumpsoverthelazydog'
        Output: True
        
        Example 2
        Input: sentence = 'leetcode'
        Output: False
        """
        for letter in "abcdefghijklmnopqrstuvwxyz":
            if letter not in sentence:
                return False
        return True


PARAM_ORDER = ['sentence']
PARAM_KINDS = {'sentence': 'plain'}
RETURN_KIND = 'plain'
EXAMPLES = [{'name': 'Example 1',
  'input': {'sentence': 'thequickbrownfoxjumpsoverthelazydog'},
  'expected': True},
 {'name': 'Example 2', 'input': {'sentence': 'leetcode'}, 'expected': False}]


def prepare_argument(name: str, value: Any) -> Any:
    """Convert one stored example input into the expected runtime value."""
    kind = PARAM_KINDS[name]
    if kind == "tree":
        return build_tree(copy.deepcopy(value))
    if kind == "listnode":
        return build_linked_list(copy.deepcopy(value))
    return copy.deepcopy(value)


def normalize_result(value: Any) -> Any:
    """Normalize a solution result back into comparable plain data."""
    if RETURN_KIND == "tree":
        return serialize_tree(value)
    if RETURN_KIND == "listnode":
        return serialize_linked_list(value)
    return value


def format_diff(expected: Any, actual: Any) -> str:
    """Render a unified diff for mismatched expected and actual values."""
    expected_lines = pprint.pformat(expected, sort_dicts=False).splitlines()
    actual_lines = pprint.pformat(actual, sort_dicts=False).splitlines()
    diff = list(
        difflib.unified_diff(
            expected_lines,
            actual_lines,
            fromfile="expected",
            tofile="actual",
            lineterm="",
        )
    )
    return "\n".join(diff) if diff else "No diff."


def run_case(case: dict[str, Any]) -> tuple[Any, Any, str | None, str | None]:
    """Execute one example case and capture any failure mode."""
    solution = Solution()
    prepared_args = [prepare_argument(name, case["input"][name]) for name in PARAM_ORDER]
    try:
        actual = solution.checkIfPangram(*prepared_args)
    except NotImplementedError as exc:
        return case["expected"], f"<not implemented: {exc}>", "not_implemented", None
    except Exception as exc:  # pragma: no cover - surfaced to the caller for debugging.
        label = f"{exc.__class__.__name__}: {exc}"
        return (
            case["expected"],
            f"<exception: {label}>",
            "exception",
            "".join(traceback.format_exception(exc)).rstrip(),
        )
    return case["expected"], normalize_result(actual), None, None


def run_examples() -> None:
    """Print each parsed example and compare it against the current solution."""
    for case in EXAMPLES:
        expected, actual, error, trace = run_case(case)
        matched = error is None and actual == expected
        print(case["name"])
        print(f"Input: {case['input']!r}")
        print(f"Expected: {expected!r}")
        print(f"Actual: {actual!r}")
        print(f"Matches expected: {matched}")
        if trace:
            print("Traceback:")
            print(trace)
        if error is not None or not matched:
            print("Diff:")
            print(format_diff(expected, actual))
        print()


class GeneratedExampleTests(unittest.TestCase):
    def test_examples(self) -> None:
        """Assert that every parsed example matches the current solution output."""
        for case in EXAMPLES:
            with self.subTest(example=case["name"]):
                expected, actual, error, trace = run_case(case)
                if error == "not_implemented":
                    self.fail(f"Solution not implemented for {case['name']}: {actual}")
                if error == "exception":
                    message = f"Solution raised an exception for {case['name']}: {actual}"
                    if trace:
                        message = f"{message}\n{trace}"
                    self.fail(message)
                self.assertEqual(expected, actual, format_diff(expected, actual))


def main() -> None:
    """Run the generated CLI entrypoint for examples or unittest mode."""
    parser = argparse.ArgumentParser(description="Run the generated LeetCode scaffold.")
    parser.add_argument("--test", action="store_true", help="Run unittest checks instead of the example runner.")
    args = parser.parse_args()
    if args.test:
        unittest.main(argv=[sys.argv[0]])
        return
    run_examples()


if __name__ == "__main__":
    main()
