from __future__ import annotations

import argparse
import copy
import difflib
import pprint
import sys
import traceback
import unittest
from typing import Any, List, Optional
from heapq import heapify, heappop, heappush


# Generated by leetcode-init

class Solution:
    def connectSticks(self, sticks: List[int]) -> int:
        """
        Return the minimum cost of connecting all the given sticks into one
        stick in this way.
        
        Examples:
        
        Example 1
        Input: sticks = [2, 4, 3]
        Output: 14
        
        Example 2
        Input: sticks = [1,8,3,5]
        Output: 30
        Explanation: You start with sticks = [1,8,3,5].
        heap = [1,3,5,8]
        stick = 1
        cur_cost = 1
        total_cost = 1
        1. Combine sticks 1 and 3 for a cost of 1 + 3 = 4. Now you have sticks = [4,8,5].
        2. Combine sticks 4 and 5 for a cost of 4 + 5 = 9. Now you have sticks = [9,8].
        3. Combine sticks 9 and 8 for a cost of 9 + 8 = 17. Now you have sticks = [17].
        There is only one stick left, so you are done. The total cost is 4 + 9 + 17 = 30.
        
        Example 3
        Input: sticks = [5]
        Output: 0
        """
        # want to collect all lowest
        heapify(sticks)
        # keep pushing/popping
        total_cost = 0
        while len(sticks) > 1:
            smallest_sticks = [heappop(sticks), heappop(sticks)]
            cur_stick = smallest_sticks[0] + smallest_sticks[1]
            total_cost += cur_stick
            heappush(sticks, cur_stick)
        return total_cost

PARAM_ORDER = ['sticks']
PARAM_KINDS = {'sticks': 'plain'}
RETURN_KIND = 'plain'
EXAMPLES = [{'name': 'Example 1', 'input': {'sticks': [2, 4, 3]}, 'expected': 14},
 {'name': 'Example 2', 'input': {'sticks': [1, 8, 3, 5]}, 'expected': 30},
 {'name': 'Example 3', 'input': {'sticks': [5]}, 'expected': 0}]


def prepare_argument(name: str, value: Any) -> Any:
    """Convert one stored example input into the expected runtime value."""
    kind = PARAM_KINDS[name]
    if kind == "tree":
        return build_tree(copy.deepcopy(value))
    if kind == "listnode":
        return build_linked_list(copy.deepcopy(value))
    return copy.deepcopy(value)


def normalize_result(value: Any) -> Any:
    """Normalize a solution result back into comparable plain data."""
    if RETURN_KIND == "tree":
        return serialize_tree(value)
    if RETURN_KIND == "listnode":
        return serialize_linked_list(value)
    return value


def format_diff(expected: Any, actual: Any) -> str:
    """Render a unified diff for mismatched expected and actual values."""
    expected_lines = pprint.pformat(expected, sort_dicts=False).splitlines()
    actual_lines = pprint.pformat(actual, sort_dicts=False).splitlines()
    diff = list(
        difflib.unified_diff(
            expected_lines,
            actual_lines,
            fromfile="expected",
            tofile="actual",
            lineterm="",
        )
    )
    return "\n".join(diff) if diff else "No diff."


def run_case(case: dict[str, Any]) -> tuple[Any, Any, str | None, str | None]:
    """Execute one example case and capture any failure mode."""
    solution = Solution()
    prepared_args = [prepare_argument(name, case["input"][name]) for name in PARAM_ORDER]
    try:
        actual = solution.connectSticks(*prepared_args)
    except NotImplementedError as exc:
        return case["expected"], f"<not implemented: {exc}>", "not_implemented", None
    except Exception as exc:  # pragma: no cover - surfaced to the caller for debugging.
        label = f"{exc.__class__.__name__}: {exc}"
        return (
            case["expected"],
            f"<exception: {label}>",
            "exception",
            "".join(traceback.format_exception(exc)).rstrip(),
        )
    return case["expected"], normalize_result(actual), None, None


def run_examples() -> None:
    """Print each parsed example and compare it against the current solution."""
    for case in EXAMPLES:
        expected, actual, error, trace = run_case(case)
        matched = error is None and actual == expected
        print(case["name"])
        print(f"Input: {case['input']!r}")
        print(f"Expected: {expected!r}")
        print(f"Actual: {actual!r}")
        print(f"Matches expected: {matched}")
        if trace:
            print("Traceback:")
            print(trace)
        if error is not None or not matched:
            print("Diff:")
            print(format_diff(expected, actual))
        print()


class GeneratedExampleTests(unittest.TestCase):
    def test_examples(self) -> None:
        """Assert that every parsed example matches the current solution output."""
        for case in EXAMPLES:
            with self.subTest(example=case["name"]):
                expected, actual, error, trace = run_case(case)
                if error == "not_implemented":
                    self.fail(f"Solution not implemented for {case['name']}: {actual}")
                if error == "exception":
                    message = f"Solution raised an exception for {case['name']}: {actual}"
                    if trace:
                        message = f"{message}\n{trace}"
                    self.fail(message)
                self.assertEqual(expected, actual, format_diff(expected, actual))


def main() -> None:
    """Run the generated CLI entrypoint for examples or unittest mode."""
    parser = argparse.ArgumentParser(description="Run the generated LeetCode scaffold.")
    parser.add_argument("--test", action="store_true", help="Run unittest checks instead of the example runner.")
    args = parser.parse_args()
    if args.test:
        unittest.main(argv=[sys.argv[0]])
        return
    run_examples()


if __name__ == "__main__":
    main()
