#!/usr/bin/env python3
import argparse
import json
import re
import subprocess
import sys
import urllib.error
import urllib.request
from collections import Counter, defaultdict
from pathlib import Path


GRAPHQL_URL = "https://leetcode.com/graphql"
README_SENTINEL = "<!-- This file is generated by scripts/update_readme.py -->"
DIFFICULTY_ORDER = ("Hard", "Medium", "Easy")
DEFAULT_DEMONSTRATES = {
    "array-string": "array mutation and pointer coordination",
    "binary-tree": "tree recursion and traversal correctness",
    "divide-and-conquer": "balanced recursive decomposition",
    "dynamic-programming": "state modeling and subproblem decomposition",
    "greedy": "greedy selection under simple constraints",
    "hash-map": "frequency counting and constant-time lookup reasoning",
    "heap": "priority-queue updates under repeated operations",
    "linked-list": "pointer manipulation and in-place rewiring",
    "stack": "stack-based validation and ordering rules",
    "strings": "two-pointer and in-place sequence mutation",
    "standalone": "problem framing without framework overhead",
}


class ProblemLookupError(RuntimeError):
    pass


class ProblemEntry:
    def __init__(
        self,
        *,
        repo_path,
        category,
        frontend_id,
        title,
        title_slug,
        difficulty,
        has_harness,
        has_test,
        demonstrates,
    ):
        self.repo_path = repo_path
        self.category = category
        self.frontend_id = str(frontend_id)
        self.title = title
        self.title_slug = title_slug
        self.difficulty = difficulty
        self.has_harness = bool(has_harness)
        self.has_test = bool(has_test)
        self.demonstrates = demonstrates


class ProblemMetadata:
    def __init__(self, *, frontend_id, title, title_slug, difficulty):
        self.frontend_id = str(frontend_id)
        self.title = title
        self.title_slug = title_slug
        self.difficulty = difficulty


class LeetCodeClient:
    QUESTION_BY_SLUG_QUERY = """
query questionTitle($titleSlug: String!) {
  question(titleSlug: $titleSlug) {
    title
    difficulty
    titleSlug
    questionFrontendId
  }
}
"""

    QUESTION_SEARCH_QUERY = """
query problemsetQuestionList(
  $categorySlug: String,
  $limit: Int,
  $skip: Int,
  $filters: QuestionListFilterInput
) {
  problemsetQuestionList: questionList(
    categorySlug: $categorySlug,
    limit: $limit,
    skip: $skip,
    filters: $filters
  ) {
    questions: data {
      title
      difficulty
      titleSlug
      questionFrontendId
    }
  }
}
"""

    def __init__(self, timeout_seconds=10):
        self.timeout_seconds = timeout_seconds

    def _post(self, query, variables):
        payload = json.dumps({"query": query, "variables": variables}).encode("utf-8")
        request = urllib.request.Request(
            GRAPHQL_URL,
            data=payload,
            headers={
                "Content-Type": "application/json",
                "Origin": "https://leetcode.com",
                "Referer": "https://leetcode.com/problemset/",
                "User-Agent": "Mozilla/5.0",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.timeout_seconds) as response:
                return json.loads(response.read().decode("utf-8"))
        except urllib.error.URLError as exc:
            raise ProblemLookupError(f"LeetCode lookup failed: {exc}") from exc

    def question_by_slug(self, title_slug):
        payload = self._post(self.QUESTION_BY_SLUG_QUERY, {"titleSlug": title_slug})
        question = payload.get("data", {}).get("question")
        if not question:
            return None
        return normalize_question_payload(question)

    def search_questions(self, keyword):
        payload = self._post(
            self.QUESTION_SEARCH_QUERY,
            {
                "categorySlug": "all-code-essentials",
                "limit": 10,
                "skip": 0,
                "filters": {"searchKeywords": keyword},
            },
        )
        questions = payload.get("data", {}).get("problemsetQuestionList", {}).get("questions", [])
        return [normalize_question_payload(question) for question in questions]

    def question_by_frontend_id(self, frontend_id):
        for question in self.search_questions(str(frontend_id)):
            if question.frontend_id == str(frontend_id):
                return question
        return None


def normalize_question_payload(question):
    return ProblemMetadata(
        frontend_id=question["questionFrontendId"],
        title=question["title"],
        title_slug=question["titleSlug"],
        difficulty=question["difficulty"],
    )


def run_git_lines(repo_root, *args):
    command = ["git", *args]
    result = subprocess.run(
        command,
        cwd=repo_root,
        check=True,
        capture_output=True,
        text=True,
    )
    return [line for line in result.stdout.splitlines() if line]


def load_overrides(override_path):
    if not override_path.exists():
        return {}
    return json.loads(override_path.read_text())


def collect_solution_paths(repo_root):
    try:
        tracked_python = run_git_lines(repo_root, "ls-files", "*.py")
    except subprocess.CalledProcessError:
        tracked_python = [
            str(path.relative_to(repo_root))
            for path in repo_root.rglob("*.py")
            if ".git" not in path.parts
        ]
    excluded_prefixes = ("tests/", "scripts/")
    return [
        path
        for path in tracked_python
        if not path.startswith(excluded_prefixes)
        and (repo_root / path).exists()
    ]


def collect_test_paths(repo_root):
    try:
        tracked_tests = run_git_lines(repo_root, "ls-files", "tests/*.py")
    except subprocess.CalledProcessError:
        tracked_tests = [str(path.relative_to(repo_root)) for path in (repo_root / "tests").rglob("*.py")] if (repo_root / "tests").exists() else []
    return [path for path in tracked_tests if path.startswith("tests/")]


def infer_category(solution_path):
    parts = Path(solution_path).parts
    if len(parts) == 1:
        return "standalone"
    return parts[0]


def infer_title_slug_candidates(solution_path):
    stem = Path(solution_path).stem
    candidates = [stem]
    trimmed = re.sub(r"^\d+-", "", stem)
    if trimmed != stem:
        candidates.append(trimmed)
    return candidates


def infer_search_keywords(solution_path):
    stem = Path(solution_path).stem
    return [stem, stem.replace("-", " "), re.sub(r"^\d+-", "", stem).replace("-", " ")]


def detect_harness(repo_root, solution_path):
    text = (repo_root / solution_path).read_text()
    return "__main__" in text


def detect_test_coverage(repo_root, solution_path, test_paths):
    path_bits = set(Path(solution_path).parts)
    stem_bits = set(Path(solution_path).stem.split("-"))
    for test_path in test_paths:
        text = (repo_root / test_path).read_text()
        if solution_path in text:
            return True
        if stem_bits and sum(bit in text for bit in stem_bits if bit) >= min(2, len(stem_bits)):
            return True
        if path_bits and sum(bit in text for bit in path_bits if bit) >= min(2, len(path_bits)):
            return True
    return False


def resolve_problem_metadata(solution_path, overrides, client):
    override = overrides.get(solution_path, {})
    frontend_id = override.get("frontend_id")
    title_slug = override.get("title_slug")

    if frontend_id:
        question = client.question_by_frontend_id(frontend_id)
        if not question:
            raise ProblemLookupError(f"Could not resolve frontend ID {frontend_id} for {solution_path}")
        return question

    filename_match = re.match(r"^(\d+)-", Path(solution_path).stem)
    if filename_match:
        question = client.question_by_frontend_id(filename_match.group(1))
        if question:
            return question

    for candidate in ([title_slug] if title_slug else []) + infer_title_slug_candidates(solution_path):
        if not candidate:
            continue
        question = client.question_by_slug(candidate)
        if question:
            return question

    for keyword in infer_search_keywords(solution_path):
        if not keyword:
            continue
        results = client.search_questions(keyword)
        if len(results) == 1:
            return results[0]
        if results:
            normalized_keyword = normalize_text(keyword)
            exact_matches = [
                result
                for result in results
                if normalize_text(result.title_slug) == normalized_keyword
                or normalize_text(result.title) == normalized_keyword
            ]
            if len(exact_matches) == 1:
                return exact_matches[0]
            raise ProblemLookupError(
                f"Ambiguous LeetCode lookup for {solution_path}: {', '.join(result.title_slug for result in results[:3])}"
            )

    raise ProblemLookupError(f"Could not resolve LeetCode metadata for {solution_path}")


def default_demonstrates(category):
    return DEFAULT_DEMONSTRATES.get(category, DEFAULT_DEMONSTRATES["standalone"])


def collect_problem_entries(repo_root, overrides_path=None, client=None):
    client = client or LeetCodeClient()
    overrides_path = overrides_path or repo_root / "scripts" / "readme_problem_overrides.json"
    overrides = load_overrides(overrides_path)
    solution_paths = collect_solution_paths(repo_root)
    test_paths = collect_test_paths(repo_root)

    problems = []
    for solution_path in solution_paths:
        metadata = resolve_problem_metadata(solution_path, overrides, client)
        category = overrides.get(solution_path, {}).get("category", infer_category(solution_path))
        demonstrates = overrides.get(solution_path, {}).get("demonstrates", default_demonstrates(category))
        problems.append(
            ProblemEntry(
                repo_path=solution_path,
                category=category,
                frontend_id=metadata.frontend_id,
                title=metadata.title,
                title_slug=metadata.title_slug,
                difficulty=metadata.difficulty,
                has_harness=detect_harness(repo_root, solution_path),
                has_test=detect_test_coverage(repo_root, solution_path, test_paths),
                demonstrates=demonstrates,
            )
        )
    return sort_problems(problems)


def difficulty_rank(problem):
    return {"Hard": 3, "Medium": 2, "Easy": 1}.get(problem.difficulty, 0)


def sort_problems(problems):
    return sorted(
        problems,
        key=lambda problem: (
            -difficulty_rank(problem),
            problem.category,
            int(problem.frontend_id),
            problem.title,
        ),
    )


def select_notable_problems(problems, limit=5):
    best_by_category = {}
    for problem in problems:
        current = best_by_category.get(problem.category)
        if current is None:
            best_by_category[problem.category] = problem
            continue
        candidate_key = (
            difficulty_rank(problem),
            problem.has_test,
            problem.has_harness,
            int(problem.frontend_id),
            problem.title,
        )
        current_key = (
            difficulty_rank(current),
            current.has_test,
            current.has_harness,
            int(current.frontend_id),
            current.title,
        )
        if candidate_key > current_key:
            best_by_category[problem.category] = problem

    return sorted(
        best_by_category.values(),
        key=lambda problem: (
            -difficulty_rank(problem),
            display_category(problem.category),
            -int(problem.frontend_id),
            problem.title,
        ),
    )


def normalize_text(value):
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def build_stats(problems, regression_test_count):
    category_counts = Counter(problem.category for problem in problems)
    difficulty_counts = Counter(problem.difficulty for problem in problems)
    return {
        "total_solved": len(problems),
        "difficulty_counts": difficulty_counts,
        "category_counts": category_counts,
        "tracked_categories": len(category_counts),
        "harness_count": sum(problem.has_harness for problem in problems),
        "regression_test_count": regression_test_count,
    }


def render_metric_table(stats):
    lines = [
        "| Metric | Count |",
        "|---|---:|",
        f"| Solved problems | {stats['total_solved']} |",
    ]
    for difficulty in DIFFICULTY_ORDER:
        count = stats["difficulty_counts"].get(difficulty, 0)
        if count:
            lines.append(f"| {difficulty} problems | {count} |")
    lines.extend(
        [
            f"| Problem categories covered | {stats['tracked_categories']} |",
        ]
    )
    return "\n".join(lines)


def render_notable_table(problems):
    lines = [
        "| Problem | Difficulty | Category | What This Demonstrates |",
        "|---|---|---|---|",
    ]
    for problem in problems:
        lines.append(
            f"| {problem.frontend_id}. {problem.title} | {problem.difficulty} | {display_category(problem.category)} | {problem.demonstrates} |"
        )
    return "\n".join(lines)


def render_category_table(stats):
    lines = ["| Category | Problems |", "|---|---:|"]
    for category, count in sorted(stats["category_counts"].items()):
        lines.append(f"| {display_category(category)} | {count} |")
    return "\n".join(lines)


def render_difficulty_tables(problems):
    grouped = defaultdict(list)
    for problem in problems:
        grouped[problem.difficulty].append(problem)

    sections = []
    for difficulty in DIFFICULTY_ORDER:
        entries = grouped.get(difficulty, [])
        if not entries:
            continue
        sections.append(f"## {difficulty}")
        lines = [
            "| Problem | Category | Repo Path | What This Demonstrates |",
            "|---|---|---|---|",
        ]
        for problem in sorted(entries, key=lambda item: (display_category(item.category), int(item.frontend_id), item.title)):
            lines.append(
                f"| {problem.frontend_id}. {problem.title} | {display_category(problem.category)} | `{problem.repo_path}` | {problem.demonstrates} |"
            )
        sections.append("\n".join(lines))
        sections.append("")
    return "\n".join(sections).rstrip()


def display_category(category):
    if category == "standalone":
        return "Standalone"
    return category.replace("-", " ").title()


def render_readme(problems, regression_test_count):
    stats = build_stats(problems, regression_test_count)
    notable = select_notable_problems(problems)
    return "\n".join(
        [
            README_SENTINEL,
            "",
            "# LeetCode Practice Repository",
            "",
            "This repository is a recruiter-friendly archive of executable LeetCode work, not a screenshot dump or a notebook of partial ideas. It shows solved problems as runnable Python files, grouped by official LeetCode difficulty so another engineer can quickly see breadth, verification habits, and the kinds of interview problems already shipped.",
            "",
            "## Why This Repo Is Worth Reviewing",
            "",
            "The strongest signal here is not just volume. It is that the repo keeps solutions inspectable as code, keeps many problems runnable with local harnesses, and now tracks them by official LeetCode difficulty so a recruiter or interviewer can scan from hardest proof down to easier coverage.",
            "",
            "## Snapshot Metrics",
            "",
            render_metric_table(stats),
            "",
            "## Notable Problems",
            "",
            render_notable_table(notable),
            "",
            "## Solved Problems By Difficulty",
            "",
            render_difficulty_tables(problems),
            "",
            "## Category Coverage",
            "",
            render_category_table(stats),
            "",
            "## Tech Stack And Why Chosen",
            "",
            "- Python 3: concise enough for interview-style implementation work and already aligned with LeetCode's common execution model.",
            "- Plain scripts plus lightweight classes: keeps each solution close to the original platform signature instead of hiding logic inside framework structure.",
            "- Standard-library `unittest`: gives the repo a small regression surface without introducing external dependencies.",
            "- A generated README workflow: turns the repository into a living portfolio surface instead of a stale list that has to be updated by hand.",
            "",
            "## Install Or Bootstrap",
            "",
            "No package install step is required. Clone the repository and use a local Python 3 interpreter.",
            "",
            "```bash",
            "git clone git@github.com:Kevin-Mok/leetcode.git",
            "cd leetcode",
            "python3 --version",
            "```",
            "",
            "## Day-To-Day Use",
            "",
            "Add a new solution under the matching topic directory, then regenerate the README so the solved-problem index, difficulty counts, and notable-problem shortlist stay current.",
            "",
            "```bash",
            "python3 scripts/update_readme.py",
            "```",
            "",
            "Run a solution directly when it has a local harness:",
            "",
            "```bash",
            "python3 binary-tree/94-binary-tree-inorder-traversal.py",
            "```",
            "",
            "Run the current regression checks:",
            "",
            "```bash",
            "python3 -m unittest discover -s tests -v",
            "```",
            "",
            "## Command Reference",
            "",
            "`python3 scripts/update_readme.py`",
            "",
            "- Rebuilds the entire root README from tracked problem files and live LeetCode difficulty data.",
            "- No repo-specific flags are required for the default write mode.",
            "",
            "`python3 scripts/update_readme.py --check`",
            "",
            "- Verifies that `README.md` already matches the generated output.",
            "- Exits nonzero when the README is stale, which makes it suitable for hooks or CI.",
            "",
            "`python3 scripts/install_pre_commit_hook.py`",
            "",
            "- Installs a local `pre-commit` hook that reruns the README generator when relevant files are staged.",
            "- No additional flags are required for the default install path.",
            "",
            "`python3 <path-to-solution>.py`",
            "",
            "- Runs a solution script directly when it includes a local `__main__` harness.",
            "- No repo-specific flags are defined for individual solution scripts.",
            "",
            "`python3 -m unittest discover -s tests -v`",
            "",
            "- `-m unittest` runs Python's built-in test runner as a module.",
            "- `discover` finds matching tests automatically.",
            "- `-s tests` limits discovery to the repo's `tests/` directory.",
            "- `-v` prints verbose test names and results.",
            "",
            "## Recruiter Notes",
            "",
            "This is intentionally not a framework-heavy application. The value is visible problem solving: recursion, dynamic programming, heap operations, pointer rewiring, and small verification loops that show how the code behaves outside the LeetCode UI.",
            "",
        ]
    )


def write_readme(readme_path, rendered):
    readme_path.write_text(rendered)


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate the root README from tracked LeetCode solutions.")
    parser.add_argument("--check", action="store_true", help="Exit nonzero if README.md is stale.")
    parser.add_argument("--repo-root", default=".", help="Repository root to inspect.")
    parser.add_argument("--override-path", default=None, help="Optional override JSON path.")
    args = parser.parse_args(argv)

    repo_root = Path(args.repo_root).resolve()
    readme_path = repo_root / "README.md"
    override_path = Path(args.override_path).resolve() if args.override_path else repo_root / "scripts" / "readme_problem_overrides.json"

    problems = collect_problem_entries(repo_root, override_path)
    regression_test_count = len(collect_test_paths(repo_root))
    rendered = render_readme(problems, regression_test_count)

    current = readme_path.read_text() if readme_path.exists() else ""
    if args.check:
        return 0 if current == rendered else 1

    if current != rendered:
        write_readme(readme_path, rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())
