#!/usr/bin/env python3
import argparse
import json
import re
import subprocess
import sys
import urllib.error
import urllib.request
from collections import Counter, defaultdict
from pathlib import Path


GRAPHQL_URL = "https://leetcode.com/graphql"
README_SENTINEL = "<!-- This file is generated by scripts/update_readme.py -->"
DIFFICULTY_ORDER = ("Hard", "Medium", "Easy")
class ProblemLookupError(RuntimeError):
    pass


class ProblemEntry:
    def __init__(
        self,
        *,
        repo_path,
        category,
        frontend_id,
        title,
        title_slug,
        difficulty,
        has_harness,
        has_test,
        demonstrates,
    ):
        self.repo_path = repo_path
        self.category = category
        self.frontend_id = str(frontend_id)
        self.title = title
        self.title_slug = title_slug
        self.difficulty = difficulty
        self.has_harness = bool(has_harness)
        self.has_test = bool(has_test)
        self.demonstrates = demonstrates


class ProblemMetadata:
    def __init__(self, *, frontend_id, title, title_slug, difficulty):
        self.frontend_id = str(frontend_id)
        self.title = title
        self.title_slug = title_slug
        self.difficulty = difficulty


class LeetCodeClient:
    QUESTION_BY_SLUG_QUERY = """
query questionTitle($titleSlug: String!) {
  question(titleSlug: $titleSlug) {
    title
    difficulty
    titleSlug
    questionFrontendId
  }
}
"""

    QUESTION_SEARCH_QUERY = """
query problemsetQuestionList(
  $categorySlug: String,
  $limit: Int,
  $skip: Int,
  $filters: QuestionListFilterInput
) {
  problemsetQuestionList: questionList(
    categorySlug: $categorySlug,
    limit: $limit,
    skip: $skip,
    filters: $filters
  ) {
    questions: data {
      title
      difficulty
      titleSlug
      questionFrontendId
    }
  }
}
"""

    def __init__(self, timeout_seconds=10):
        self.timeout_seconds = timeout_seconds

    def _post(self, query, variables):
        payload = json.dumps({"query": query, "variables": variables}).encode("utf-8")
        request = urllib.request.Request(
            GRAPHQL_URL,
            data=payload,
            headers={
                "Content-Type": "application/json",
                "Origin": "https://leetcode.com",
                "Referer": "https://leetcode.com/problemset/",
                "User-Agent": "Mozilla/5.0",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=self.timeout_seconds) as response:
                return json.loads(response.read().decode("utf-8"))
        except urllib.error.URLError as exc:
            raise ProblemLookupError(f"LeetCode lookup failed: {exc}") from exc

    def question_by_slug(self, title_slug):
        payload = self._post(self.QUESTION_BY_SLUG_QUERY, {"titleSlug": title_slug})
        question = payload.get("data", {}).get("question")
        if not question:
            return None
        return normalize_question_payload(question)

    def search_questions(self, keyword):
        payload = self._post(
            self.QUESTION_SEARCH_QUERY,
            {
                "categorySlug": "all-code-essentials",
                "limit": 10,
                "skip": 0,
                "filters": {"searchKeywords": keyword},
            },
        )
        questions = payload.get("data", {}).get("problemsetQuestionList", {}).get("questions", [])
        return [normalize_question_payload(question) for question in questions]

    def question_by_frontend_id(self, frontend_id):
        for question in self.search_questions(str(frontend_id)):
            if question.frontend_id == str(frontend_id):
                return question
        return None


def normalize_question_payload(question):
    return ProblemMetadata(
        frontend_id=question["questionFrontendId"],
        title=question["title"],
        title_slug=question["titleSlug"],
        difficulty=question["difficulty"],
    )


def run_git_lines(repo_root, *args):
    command = ["git", *args]
    result = subprocess.run(
        command,
        cwd=repo_root,
        check=True,
        capture_output=True,
        text=True,
    )
    return [line for line in result.stdout.splitlines() if line]


def load_overrides(override_path):
    if not override_path.exists():
        return {}
    return json.loads(override_path.read_text())


def collect_solution_paths(repo_root):
    try:
        tracked_python = run_git_lines(repo_root, "ls-files", "*.py")
    except subprocess.CalledProcessError:
        tracked_python = [
            str(path.relative_to(repo_root))
            for path in repo_root.rglob("*.py")
            if ".git" not in path.parts
        ]
    excluded_prefixes = ("tests/", "scripts/")
    return [
        path
        for path in tracked_python
        if not path.startswith(excluded_prefixes)
        and (repo_root / path).exists()
    ]


def collect_test_paths(repo_root):
    try:
        tracked_tests = run_git_lines(repo_root, "ls-files", "tests/*.py")
    except subprocess.CalledProcessError:
        tracked_tests = [str(path.relative_to(repo_root)) for path in (repo_root / "tests").rglob("*.py")] if (repo_root / "tests").exists() else []
    return [path for path in tracked_tests if path.startswith("tests/")]


def infer_category(solution_path):
    parts = Path(solution_path).parts
    if len(parts) == 1:
        return "standalone"
    return parts[0]


def infer_title_slug_candidates(solution_path):
    stem = Path(solution_path).stem
    candidates = [stem]
    trimmed = re.sub(r"^\d+-", "", stem)
    if trimmed != stem:
        candidates.append(trimmed)
    return candidates


def infer_search_keywords(solution_path):
    stem = Path(solution_path).stem
    return [stem, stem.replace("-", " "), re.sub(r"^\d+-", "", stem).replace("-", " ")]


def detect_harness(repo_root, solution_path):
    text = (repo_root / solution_path).read_text()
    return "__main__" in text


def detect_test_coverage(repo_root, solution_path, test_paths):
    path_bits = set(Path(solution_path).parts)
    stem_bits = set(Path(solution_path).stem.split("-"))
    for test_path in test_paths:
        text = (repo_root / test_path).read_text()
        if solution_path in text:
            return True
        if stem_bits and sum(bit in text for bit in stem_bits if bit) >= min(2, len(stem_bits)):
            return True
        if path_bits and sum(bit in text for bit in path_bits if bit) >= min(2, len(path_bits)):
            return True
    return False


def resolve_problem_metadata(solution_path, overrides, client):
    override = overrides.get(solution_path, {})
    frontend_id = override.get("frontend_id")
    title_slug = override.get("title_slug")

    if frontend_id:
        question = client.question_by_frontend_id(frontend_id)
        if not question:
            raise ProblemLookupError(f"Could not resolve frontend ID {frontend_id} for {solution_path}")
        return question

    filename_match = re.match(r"^(\d+)-", Path(solution_path).stem)
    if filename_match:
        question = client.question_by_frontend_id(filename_match.group(1))
        if question:
            return question

    for candidate in ([title_slug] if title_slug else []) + infer_title_slug_candidates(solution_path):
        if not candidate:
            continue
        question = client.question_by_slug(candidate)
        if question:
            return question

    for keyword in infer_search_keywords(solution_path):
        if not keyword:
            continue
        results = client.search_questions(keyword)
        if len(results) == 1:
            return results[0]
        if results:
            normalized_keyword = normalize_text(keyword)
            exact_matches = [
                result
                for result in results
                if normalize_text(result.title_slug) == normalized_keyword
                or normalize_text(result.title) == normalized_keyword
            ]
            if len(exact_matches) == 1:
                return exact_matches[0]
            raise ProblemLookupError(
                f"Ambiguous LeetCode lookup for {solution_path}: {', '.join(result.title_slug for result in results[:3])}"
            )

    raise ProblemLookupError(f"Could not resolve LeetCode metadata for {solution_path}")


def read_problem_statement(repo_root, solution_path):
    prompt_path = repo_root / Path(solution_path).with_suffix(".txt")
    if not prompt_path.exists():
        return ""
    text = prompt_path.read_text()
    if "Solution" in text:
        text = text.split("Solution", 1)[1]
    text = text.split("Example 1:", 1)[0]
    return " ".join(line.strip() for line in text.splitlines() if line.strip())


def infer_from_statement(statement, title):
    lowered = statement.lower()
    title_lower = title.lower()
    patterns = [
        (
            "inorder traversal",
            "walking a binary tree in left-root-right order and returning the visited values",
        ),
        (
            "invert the tree",
            "inverting a binary tree and returning the flipped root structure",
        ),
        (
            "simplified canonical path",
            "canonical path normalization that collapses '.', '..', and repeated slashes",
        ),
        (
            "middle node",
            "single-pass linked-list traversal that returns the second middle when the length is even",
        ),
        (
            "minimum cost of connecting all the given sticks",
            "repeated cheapest-pair stick merges that minimize the total connection cost",
        ),
        (
            "search insert position",
            "finding a target index or the sorted insertion point when the value is absent",
        ),
        (
            "deci-binary",
            "reducing the answer to the largest digit instead of simulating each deci-binary number",
        ),
        (
            "pangram",
            "checking whether every lowercase letter appears at least once in the sentence",
        ),
    ]
    for needle, description in patterns:
        if needle in lowered or needle in title_lower:
            return description
    return ""


def infer_from_title(title, category):
    title_lower = title.lower()
    title_patterns = [
        ("merge sorted array", "merging two sorted inputs in place from the back of the destination array"),
        ("longest subsequence with limited sum", "prefix-sum preprocessing plus binary-search queries against a running sum budget"),
        ("search insert position", "finding a target index or the sorted insertion point when the value is absent"),
        ("minimum depth of binary tree", "stopping at the first leaf depth instead of miscounting missing-child branches"),
        ("invert binary tree", "inverting a binary tree and returning the flipped root structure"),
        ("binary tree inorder traversal", "walking a binary tree in left-root-right order and returning the visited values"),
        ("convert sorted array to binary search tree", "choosing midpoint roots recursively to keep the binary search tree height-balanced"),
        ("longest increasing subsequence", "tracking the best increasing subsequence length that can end at each position"),
        ("coin change", "building the minimum-coin answer for each amount up to the target"),
        ("all possible full binary trees", "reusing subproblem results to enumerate every full binary-tree shape of a given size"),
        ("partitioning into minimum number of deci-binary numbers", "reducing the answer to the largest digit instead of constructing every deci-binary addend"),
        ("minimum sum of four digit number after splitting digits", "sorting digits and distributing small digits across both numbers to minimize the total"),
        ("check if the sentence is pangram", "checking whether every lowercase letter appears at least once in the sentence"),
        ("ransom note", "counting character supply versus demand to decide whether construction is possible"),
        ("minimum cost to connect sticks", "repeated cheapest-pair stick merges that minimize the total connection cost"),
        ("remove stones to minimize the total", "repeatedly reducing the largest pile so the remaining total drops as fast as possible"),
        ("merge two sorted lists", "pointer-by-pointer merging that preserves sorted order without rebuilding the list"),
        ("remove duplicates from sorted list", "removing repeated linked-list values in place while keeping one copy of each"),
        ("middle of the linked list", "single-pass linked-list traversal that returns the second middle when the length is even"),
        ("moving average from data stream", "maintaining a fixed-size running window while updating the average for each new value"),
        ("valid parentheses", "verifying nested bracket order with stack-based matching rules"),
        ("reverse string", "reversing the character array in place with two-pointer swaps"),
        ("squares of a sorted array", "filling sorted squared values by comparing absolute values from both ends"),
        ("simplify path", "canonical path normalization that collapses '.', '..', and repeated slashes"),
    ]
    for needle, description in title_patterns:
        if needle in title_lower:
            return description
    category_defaults = {
        "binary-tree": f"solving {title_lower} with recursive binary-tree state management",
        "linked-list": f"solving {title_lower} with pointer-safe linked-list traversal",
        "heap": f"solving {title_lower} with heap-driven prioritization",
        "dynamic-programming": f"solving {title_lower} with explicit subproblem state transitions",
        "binary-search": f"solving {title_lower} with sorted-order search boundaries",
        "stack": f"solving {title_lower} with stack-managed ordering rules",
    }
    return category_defaults.get(category, f"solving {title_lower} under interview-style constraints")


def infer_demonstrates(repo_root, solution_path, metadata, category):
    statement = read_problem_statement(repo_root, solution_path)
    inferred = infer_from_statement(statement, metadata.title)
    if inferred:
        return inferred
    return infer_from_title(metadata.title, category)


def resolve_demonstrates(repo_root, solution_path, overrides, metadata, category):
    demonstrates = overrides.get(solution_path, {}).get("demonstrates")
    if demonstrates:
        return demonstrates
    return infer_demonstrates(repo_root, solution_path, metadata, category)


def collect_problem_entries(repo_root, overrides_path=None, client=None):
    client = client or LeetCodeClient()
    overrides_path = overrides_path or repo_root / "scripts" / "readme_problem_overrides.json"
    overrides = load_overrides(overrides_path)
    solution_paths = collect_solution_paths(repo_root)
    test_paths = collect_test_paths(repo_root)

    problems = []
    for solution_path in solution_paths:
        metadata = resolve_problem_metadata(solution_path, overrides, client)
        category = overrides.get(solution_path, {}).get("category", infer_category(solution_path))
        demonstrates = resolve_demonstrates(repo_root, solution_path, overrides, metadata, category)
        problems.append(
            ProblemEntry(
                repo_path=solution_path,
                category=category,
                frontend_id=metadata.frontend_id,
                title=metadata.title,
                title_slug=metadata.title_slug,
                difficulty=metadata.difficulty,
                has_harness=detect_harness(repo_root, solution_path),
                has_test=detect_test_coverage(repo_root, solution_path, test_paths),
                demonstrates=demonstrates,
            )
        )
    return sort_problems(problems)


def difficulty_rank(problem):
    return {"Hard": 3, "Medium": 2, "Easy": 1}.get(problem.difficulty, 0)


def sort_problems(problems):
    return sorted(
        problems,
        key=lambda problem: (
            -difficulty_rank(problem),
            problem.category,
            int(problem.frontend_id),
            problem.title,
        ),
    )


def select_notable_problems(problems, limit=5):
    best_by_category = {}
    for problem in problems:
        current = best_by_category.get(problem.category)
        if current is None:
            best_by_category[problem.category] = problem
            continue
        candidate_key = (
            difficulty_rank(problem),
            problem.has_test,
            problem.has_harness,
            int(problem.frontend_id),
            problem.title,
        )
        current_key = (
            difficulty_rank(current),
            current.has_test,
            current.has_harness,
            int(current.frontend_id),
            current.title,
        )
        if candidate_key > current_key:
            best_by_category[problem.category] = problem

    return sorted(
        best_by_category.values(),
        key=lambda problem: (
            -difficulty_rank(problem),
            display_category(problem.category),
            -int(problem.frontend_id),
            problem.title,
        ),
    )


def normalize_text(value):
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def build_stats(problems, regression_test_count):
    category_counts = Counter(problem.category for problem in problems)
    difficulty_counts = Counter(problem.difficulty for problem in problems)
    return {
        "total_solved": len(problems),
        "difficulty_counts": difficulty_counts,
        "category_counts": category_counts,
        "tracked_categories": len(category_counts),
        "harness_count": sum(problem.has_harness for problem in problems),
        "regression_test_count": regression_test_count,
    }


def render_metric_table(stats):
    lines = [
        "| Metric | Count |",
        "|---|---:|",
        f"| Solved problems | {stats['total_solved']} |",
    ]
    for difficulty in DIFFICULTY_ORDER:
        count = stats["difficulty_counts"].get(difficulty, 0)
        if count:
            lines.append(f"| {difficulty} problems | {count} |")
    lines.extend(
        [
            f"| Problem categories covered | {stats['tracked_categories']} |",
            f"| Runnable local harnesses | {stats['harness_count']} |",
            f"| Problems with detected regression coverage | {stats['regression_test_count']} |",
        ]
    )
    return "\n".join(lines)


def render_problem_link(problem):
    return f"[{problem.frontend_id}. {problem.title}]({problem.repo_path})"


def render_category_link(category):
    category_path = "." if category == "standalone" else category
    return f"[{display_category(category)}]({category_path})"


def render_notable_table(problems):
    lines = [
        "| Problem | Difficulty | Category | What This Demonstrates |",
        "|---|---|---|---|",
    ]
    for problem in problems:
        lines.append(
            f"| {render_problem_link(problem)} | {problem.difficulty} | {render_category_link(problem.category)} | {problem.demonstrates} |"
        )
    return "\n".join(lines)


def render_category_table(stats):
    lines = ["| Category | Problems |", "|---|---:|"]
    for category, count in sorted(stats["category_counts"].items()):
        lines.append(f"| {render_category_link(category)} | {count} |")
    return "\n".join(lines)


def render_difficulty_tables(problems):
    grouped = defaultdict(list)
    for problem in problems:
        grouped[problem.difficulty].append(problem)

    sections = []
    for difficulty in DIFFICULTY_ORDER:
        entries = grouped.get(difficulty, [])
        if not entries:
            continue
        sections.append(f"## {difficulty}")
        lines = [
            "| Problem | Category | What This Demonstrates |",
            "|---|---|---|",
        ]
        for problem in sorted(entries, key=lambda item: (display_category(item.category), int(item.frontend_id), item.title)):
            lines.append(
                f"| {render_problem_link(problem)} | {render_category_link(problem.category)} | {problem.demonstrates} |"
            )
        sections.append("\n".join(lines))
        sections.append("")
    return "\n".join(sections).rstrip()


def display_category(category):
    if category == "standalone":
        return "Standalone"
    return category.replace("-", " ").title()


def render_readme(problems, regression_test_count):
    stats = build_stats(problems, regression_test_count)
    notable = select_notable_problems(problems)
    return "\n".join(
        [
            README_SENTINEL,
            "",
            "# LeetCode Practice Repository",
            "",
            "This repository turns LeetCode practice into recruiter-facing proof: executable Python solutions, local verification harnesses, and official difficulty grouping that make problem-solving breadth easy to inspect instead of hand-wave. The proof surface is technical rather than presentational: arrays and strings, stacks, hash maps, heaps, linked lists, binary trees, divide-and-conquer recursion, and dynamic-programming state transitions are all represented as runnable Python files instead of screenshots or one-line claims.",
            "",
            "The README is generated from tracked solution files plus live LeetCode metadata, so solved counts, difficulty buckets, category coverage, and notable examples stay aligned with the repository instead of drifting as more problems get added.",
            "",
            "## Recruiter Proof Surface",
            "",
            "- Arrays, strings, and two-pointer work show in-place mutation and index coordination under interview-style constraints.",
            "- Stacks, hash maps, and heaps show the standard lookup and ordering primitives that recur in screening rounds.",
            "- Linked lists and binary trees show pointer rewiring, traversal correctness, and recursive decomposition without framework scaffolding.",
            "- Dynamic programming and divide-and-conquer entries show state modeling, subproblem reuse, and recurrence-driven reasoning.",
            "- Generated metrics and notable-problem tables turn the repo into a durable evidence surface instead of a manually curated brag list.",
            "",
            "## Snapshot Metrics",
            "",
            render_metric_table(stats),
            "",
            "## Notable Problems",
            "",
            render_notable_table(notable),
            "",
            "## Solved Problems By Difficulty",
            "",
            render_difficulty_tables(problems),
            "",
            "## Category Coverage",
            "",
            render_category_table(stats),
            "",
            "## Tech Stack And Why Chosen",
            "",
            "- Python 3: concise enough for interview-style implementation work, but still explicit enough to show pointer logic, recursion, heap operations, and dynamic-programming table updates clearly.",
            "- Plain scripts plus lightweight classes: keeps each solution close to the LeetCode function or class signature, which makes the algorithmic core easy to inspect without framework noise.",
            "- Standard-library `unittest`: provides lightweight regression checks for the local harnesses and README generator without adding dependency overhead.",
            "- Generated README workflow backed by tracked files and live difficulty metadata: keeps the recruiter-facing proof synchronized with the actual codebase instead of relying on manual README edits.",
            "",
            "## Install Or Bootstrap",
            "",
            "No package install step is required. Clone the repository and use a local Python 3 interpreter.",
            "",
            "```bash",
            "git clone git@github.com:Kevin-Mok/leetcode.git",
            "cd leetcode",
            "python3 --version",
            "```",
            "",
            "## Day-To-Day Use",
            "",
            "Add a new solution under the matching topic directory, refresh the local LeetCode catalog when you want the full problem list on disk, then regenerate the README so the solved-problem index, difficulty counts, and notable-problem shortlist stay current.",
            "",
            "The downloaded catalog lives at `data/leetcode-problem-catalog.json`.",
            "",
            "```bash",
            "python3 scripts/download_problem_catalog.py",
            "```",
            "",
            "```bash",
            "python3 scripts/update_readme.py",
            "```",
            "",
            "Run a solution directly when it has a local harness:",
            "",
            "```bash",
            "python3 binary-tree/94-binary-tree-inorder-traversal.py",
            "```",
            "",
            "Run the current regression checks:",
            "",
            "```bash",
            "python3 -m unittest discover -s tests -v",
            "```",
            "",
            "Dry-run the worktree merge helper before shipping a feature branch back to `main`:",
            "",
            "```bash",
            "python3 scripts/merge_worktree_to_main.py --dry-run",
            "```",
            "",
            "## Command Reference",
            "",
            "`python3 scripts/update_readme.py`",
            "",
            "- Rebuilds the entire root README from tracked problem files and live LeetCode difficulty data.",
            "- No repo-specific flags are required for the default write mode.",
            "",
            "`python3 scripts/update_readme.py --check`",
            "",
            "- Verifies that `README.md` already matches the generated output.",
            "- Exits nonzero when the README is stale, which makes it suitable for hooks or CI.",
            "",
            "`python3 scripts/download_problem_catalog.py`",
            "",
            "- Downloads the current LeetCode problem catalog and writes it to `data/leetcode-problem-catalog.json`.",
            "- Supports `--output <path>` if you want to write the catalog somewhere else.",
            "",
            "`python3 scripts/install_pre_commit_hook.py`",
            "",
            "- Installs a local `pre-commit` hook that reruns the README generator when relevant files are staged.",
            "- No additional flags are required for the default install path.",
            "",
            "`python3 scripts/merge_worktree_to_main.py`",
            "",
            "- Verifies the latest changed LeetCode solution file against its local `--test` harness before merging the current worktree branch into `main` and pushing `origin main`.",
            "- Supports `--dry-run` to print the exact merge sequence without mutating git state.",
            "- Supports `--keep-branch`, `--keep-worktree`, and `--base-branch <name>` when you want to preserve cleanup state or target a different base branch.",
            "",
            "`python3 <path-to-solution>.py`",
            "",
            "- Runs a solution script directly when it includes a local `__main__` harness.",
            "- No repo-specific flags are defined for individual solution scripts.",
            "",
            "`python3 -m unittest discover -s tests -v`",
            "",
            "- `-m unittest` runs Python's built-in test runner as a module.",
            "- `discover` finds matching tests automatically.",
            "- `-s tests` limits discovery to the repo's `tests/` directory.",
            "- `-v` prints verbose test names and results.",
            "",
        ]
    )


def write_readme(readme_path, rendered):
    readme_path.write_text(rendered)


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate the root README from tracked LeetCode solutions.")
    parser.add_argument("--check", action="store_true", help="Exit nonzero if README.md is stale.")
    parser.add_argument("--repo-root", default=".", help="Repository root to inspect.")
    parser.add_argument("--override-path", default=None, help="Optional override JSON path.")
    args = parser.parse_args(argv)

    repo_root = Path(args.repo_root).resolve()
    readme_path = repo_root / "README.md"
    override_path = Path(args.override_path).resolve() if args.override_path else repo_root / "scripts" / "readme_problem_overrides.json"

    problems = collect_problem_entries(repo_root, override_path)
    regression_test_count = len(collect_test_paths(repo_root))
    rendered = render_readme(problems, regression_test_count)

    current = readme_path.read_text() if readme_path.exists() else ""
    if args.check:
        return 0 if current == rendered else 1

    if current != rendered:
        write_readme(readme_path, rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())
