from __future__ import annotations

import argparse
import copy
import difflib
import pprint
import sys
import traceback
import unittest
from typing import Any, List, Optional


# Generated by leetcode-init



class Solution:
    def answerQueries(self, nums: List[int], queries: List[int]) -> List[int]:
        """
        You are given an integer array nums of length n, and an integer array
        queries of length m.
        
        Return an array answer of length m where answer[i] is the maximum size
        of a subsequence that you can take from nums such that the sum of its
        elements is less than or equal to queries[i].
        
        A subsequence is an array that can be derived from another array by
        deleting some or no elements without changing the order of the
        remaining elements.
        
        Examples:
        
        Example 1
        Input: nums = [4, 5, 2, 1], queries = [3, 10, 21]
        Output: [2, 3, 4]
        
        Example 2
        Input: nums = [2, 3, 4, 5], queries = [1]
        Output: [0]
        """
        nums.sort()
        # Good first step: if you want the longest subsequence under a sum limit,
        # taking the smallest values first is always optimal.
        sorted_nums = nums

        # Hint: the binary-search target should usually be "how many smallest
        # numbers can I afford?", not the raw values themselves.
        #
        # A common setup is:
        # 1. Build prefix sums of sorted_nums.
        # 2. For each query, binary search for the rightmost prefix sum <= query.
        # 3. That index (+ 1) is the answer length.
        max_subseq = []
        for max_sum in queries:
            # Hint: this `right` pointer is currently being treated like both an
            # index and an answer length. Pick one meaning and keep it consistent.
            right = len(sorted_nums) - 1

            # Hint: slicing and calling sum(...) inside the loop makes the search
            # harder to reason about. Prefix sums let each midpoint check be O(1).
            nums_subseq = sorted_nums[:right]
            nums_subseq_sum = sum(nums_subseq)

            # Hint: this should probably add the "next array value", not the
            # index `right`. Right now you're mixing positions with numbers.
            next_subseq_sum = (nums_subseq_sum + 
                               (right 
                                if right < len(sorted_nums) - 1 
                                else 0))
            while next_subseq_sum > max_sum:
                # Hint: ask "is the sum of the first k sorted numbers <= query?"
                # That yes/no question is monotonic, which is exactly why binary
                # search works here.
                if nums_subseq_sum > max_sum:
                    right = right // 2
                elif nums_subseq_sum <= max_sum:
                   mid_right = (right + (len(sorted_nums) - 1)) // 2
                   right = mid_right
                nums_subseq = sorted_nums[:right]
                nums_subseq_sum = sum(nums_subseq)
                next_subseq_sum = (nums_subseq_sum + 
                                  (right 
                                   if right < len(sorted_nums) - 1 
                                   else 0))
            # Hint: once your search is over prefix sums, you should not need a
            # special-case subtraction here. The final binary-search position
            # directly maps to the subsequence length.
            max_subseq.append(len(sorted_nums) 
                              if right == len(sorted_nums) - 1 
                               else right - 1)

        return max_subseq


PARAM_ORDER = ['nums', 'queries']
PARAM_KINDS = {'nums': 'plain', 'queries': 'plain'}
RETURN_KIND = 'plain'
EXAMPLES = [{'name': 'Example 1',
  'input': {'nums': [4, 5, 2, 1], 'queries': [3, 10, 21]},
  'expected': [2, 3, 4]},
 {'name': 'Example 2',
  'input': {'nums': [2, 3, 4, 5], 'queries': [1]},
  'expected': [0]}]


def prepare_argument(name: str, value: Any) -> Any:
    """Convert one stored example input into the expected runtime value."""
    kind = PARAM_KINDS[name]
    if kind == "tree":
        return build_tree(copy.deepcopy(value))
    if kind == "listnode":
        return build_linked_list(copy.deepcopy(value))
    return copy.deepcopy(value)


def normalize_result(value: Any) -> Any:
    """Normalize a solution result back into comparable plain data."""
    if RETURN_KIND == "tree":
        return serialize_tree(value)
    if RETURN_KIND == "listnode":
        return serialize_linked_list(value)
    return value


def format_diff(expected: Any, actual: Any) -> str:
    """Render a unified diff for mismatched expected and actual values."""
    expected_lines = pprint.pformat(expected, sort_dicts=False).splitlines()
    actual_lines = pprint.pformat(actual, sort_dicts=False).splitlines()
    diff = list(
        difflib.unified_diff(
            expected_lines,
            actual_lines,
            fromfile="expected",
            tofile="actual",
            lineterm="",
        )
    )
    return "\n".join(diff) if diff else "No diff."


def run_case(case: dict[str, Any]) -> tuple[Any, Any, str | None, str | None]:
    """Execute one example case and capture any failure mode."""
    solution = Solution()
    prepared_args = [prepare_argument(name, case["input"][name]) for name in PARAM_ORDER]
    try:
        actual = solution.answerQueries(*prepared_args)
    except NotImplementedError as exc:
        return case["expected"], f"<not implemented: {exc}>", "not_implemented", None
    except Exception as exc:  # pragma: no cover - surfaced to the caller for debugging.
        label = f"{exc.__class__.__name__}: {exc}"
        return (
            case["expected"],
            f"<exception: {label}>",
            "exception",
            "".join(traceback.format_exception(exc)).rstrip(),
        )
    return case["expected"], normalize_result(actual), None, None


def run_examples() -> None:
    """Print each parsed example and compare it against the current solution."""
    for case in EXAMPLES:
        expected, actual, error, trace = run_case(case)
        matched = error is None and actual == expected
        print(case["name"])
        print(f"Input: {case['input']!r}")
        print(f"Expected: {expected!r}")
        print(f"Actual: {actual!r}")
        print(f"Matches expected: {matched}")
        if trace:
            print("Traceback:")
            print(trace)
        if error is not None or not matched:
            print("Diff:")
            print(format_diff(expected, actual))
        print()


class GeneratedExampleTests(unittest.TestCase):
    def test_examples(self) -> None:
        """Assert that every parsed example matches the current solution output."""
        for case in EXAMPLES:
            with self.subTest(example=case["name"]):
                expected, actual, error, trace = run_case(case)
                if error == "not_implemented":
                    self.fail(f"Solution not implemented for {case['name']}: {actual}")
                if error == "exception":
                    message = f"Solution raised an exception for {case['name']}: {actual}"
                    if trace:
                        message = f"{message}\n{trace}"
                    self.fail(message)
                self.assertEqual(expected, actual, format_diff(expected, actual))


def main() -> None:
    """Run the generated CLI entrypoint for examples or unittest mode."""
    parser = argparse.ArgumentParser(description="Run the generated LeetCode scaffold.")
    parser.add_argument("--test", action="store_true", help="Run unittest checks instead of the example runner.")
    args = parser.parse_args()
    if args.test:
        unittest.main(argv=[sys.argv[0]])
        return
    run_examples()


if __name__ == "__main__":
    main()
